Also support zst.

diff --git a/.github/workflows/Nightly.yml b/.github/workflows/Nightly.yml
--- a/.github/workflows/Nightly.yml
+++ b/.github/workflows/Nightly.yml
@@ -86,6 +86,9 @@ jobs:
           # The command 'git describe' (used for version) needs the history.
           fetch-depth: 0
 
+      - name: 🔧 Install zstd
+        run: sudo apt-get install -y --no-install-recommends zstd
+
       - name: 📑 Delete (old) Release Page
         id: deleteReleasePage
         run: |
@@ -226,37 +229,51 @@ jobs:
 
             # Check if artifact should be compressed (zip, tgz) or if asset was part of the downloaded artifact.
             echo -n "  checking asset '${artifact}/${asset}' ... "
-            if [[ "${asset}" == !*zip ]]; then
+            if [[ "${asset}" == !*.zip ]]; then
               echo -e "${ANSI_LIGHT_GREEN}[ZIP]${ANSI_NOCOLOR}"
               asset="${asset##*!}"
               echo "    Compressing artifact '${artifact}' to '${asset}' ..."
               cd "${artifact}"
               zip -r "../${asset}" *
+              retCode=$?
               cd -
-              if [[ $? -eq 0 ]]; then
+              if [[ $retCode -eq 0 ]]; then
                 echo -e "    Compression ${ANSI_LIGHT_GREEN}[OK]${ANSI_NOCOLOR}"
                 uploadFile="${asset}"
               else
                 echo -e "    Compression ${ANSI_LIGHT_RED}[ERROR]${ANSI_NOCOLOR}"
                 echo "Couldn't compress '${artifact}' to zip file '${asset}'."
-                echo "::error title=ZipError::Couldn't compress '${artifact}' to zip file '${asset}'."
+                echo "::error title=CompressionError::Couldn't compress '${artifact}' to zip file '${asset}'."
                 ERRORS=1
                 continue
               fi
-            elif [[ "${asset}" == !*tgz ]]; then
+            elif [[ "${asset}" == !*.tgz || "${asset}" == !*.tar.gz ]]; then
               echo -e "${ANSI_LIGHT_GREEN}[TAR/GZ]${ANSI_NOCOLOR}"
               asset="${asset##*!}"
               echo "    Compressing artifact '${artifact}' to '${asset}' ..."
-              cd "${artifact}"
-              tar -czf "../${asset}" *
-              cd -
+              tar -c --gzip --file="../${asset}" --directory="${artifact}" .
               if [[ $? -eq 0 ]]; then
                 echo -e "    Compression ${ANSI_LIGHT_GREEN}[OK]${ANSI_NOCOLOR}"
                 uploadFile="${asset}"
               else
                 echo -e "    Compression ${ANSI_LIGHT_RED}[ERROR]${ANSI_NOCOLOR}"
                 echo "Couldn't compress '${artifact}' to tgz file '${asset}'."
-                echo "::error title=ZipError::Couldn't compress '${artifact}' to tgz file '${asset}'."
+                echo "::error title=CompressionError::Couldn't compress '${artifact}' to tgz file '${asset}'."
+                ERRORS=1
+                continue
+              fi
+            elif [[ "${asset}" == !*.tzst || "${asset}" == !*.tar.zst ]]; then
+              echo -e "${ANSI_LIGHT_GREEN}[ZST]${ANSI_NOCOLOR}"
+              asset="${asset##*!}"
+              echo "    Compressing artifact '${artifact}' to '${asset}' ..."
+              tar -c --zstd --file="../${asset}" --directory="${artifact}" --transform 's|^\.|ghdl|' .
+              if [[ $? -eq 0 ]]; then
+                echo -e "    Compression ${ANSI_LIGHT_GREEN}[OK]${ANSI_NOCOLOR}"
+                uploadFile="${asset}"
+              else
+                echo -e "    Compression ${ANSI_LIGHT_RED}[ERROR]${ANSI_NOCOLOR}"
+                echo "Couldn't compress '${artifact}' to zst file '${asset}'."
+                echo "::error title=CompressionError::Couldn't compress '${artifact}' to zst file '${asset}'."
                 ERRORS=1
                 continue
               fi
