Allow pre-releases and user-defined descriptions.

diff --git a/.github/workflows/Nightly.yml b/.github/workflows/Nightly.yml
--- a/.github/workflows/Nightly.yml
+++ b/.github/workflows/Nightly.yml
@@ -35,6 +35,31 @@ on:
         required: false
         default: 'nightly'
         type: string
+      nightly_title:
+        description: 'Title of the nightly release.'
+        required: false
+        default: ''
+        type: string
+      nightly_description:
+        description: 'Description of the nightly release.'
+        required: false
+        default: 'Release of artifacts from latest CI pipeline.'
+        type: string
+      draft:
+        description: 'Specify if this is a draft.'
+        required: false
+        default: false
+        type: boolean
+      prerelease:
+        description: 'Specify if this is a pre-release.'
+        required: false
+        default: false
+        type: boolean
+      latest:
+        description: 'Specify if this is the latest release.'
+        required: false
+        default: false
+        type: boolean
       assets:
         description: 'Multi-line string containing artifact:file:title asset descriptions.'
         required: true
@@ -64,20 +89,25 @@ jobs:
       - name: 📑 Delete (old) Release Page
         id: deleteReleasePage
         run: |
+          set +e
+          
           ANSI_LIGHT_RED="\e[91m"
           ANSI_LIGHT_GREEN="\e[92m"
+          ANSI_LIGHT_YELLOW="\e[93m"
           ANSI_NOCOLOR="\e[0m"
           
           export GH_TOKEN=${{ github.token }}
           
           echo -n "Deleting release '${{ inputs.nightly_name }}' ... "
-          gh release delete ${{ inputs.nightly_name }} --yes
+          message="$(gh release delete ${{ inputs.nightly_name }} --yes 2>&1)"
           if [[ $? -eq 0 ]]; then
             echo -e "${ANSI_LIGHT_GREEN}[OK]${ANSI_NOCOLOR}"
+          elif [[ "${message}" == "release not found" ]]; then
+            echo -e "${ANSI_LIGHT_YELLOW}[NOT FOUND]${ANSI_NOCOLOR}"        
           else
             echo -e "${ANSI_LIGHT_RED}[FAILED]${ANSI_NOCOLOR}"
-            echo "Couldn't delete release '${{ inputs.nightly_name }}'."
-            echo "::error title=APIError::Couldn't delete release '${{ inputs.nightly_name }}'."
+            echo "Couldn't delete release '${{ inputs.nightly_name }}' -> Error: '${message}'."
+            echo "::error title=InternalError::Couldn't delete release '${{ inputs.nightly_name }}'."
             exit 1
           fi
 
@@ -90,19 +120,39 @@ jobs:
           
           export GH_TOKEN=${{ github.token }}
           
+          if ${{ inputs.draft }}; then
+            addDraft="--draft"
+          fi
+          
+          if ${{ inputs.prerelease }}; then
+            addPreRelease="--prerelease"
+          fi
+          
+          if ! ${{ inputs.latest }}; then
+            addLatest="--latest=false"
+          fi
+          
+          if [[ "${{ inputs.nightly_title }}" != "" ]]; then
+            addTitle="--title '${{ inputs.nightly_title }}'"
+          fi
+          
+          cat <<'EOF' > __NoTeS__.md 
+          ${{ inputs.nightly_description }}
+          EOF
+          if [[ -s __NoTeS__.md ]]; then
+            addNotes="--notes-file -"
+          fi
+          
           echo "Creating release '${{ inputs.nightly_name }}' ... "
-          gh release create ${{ inputs.nightly_name }} --verify-tag --notes "Testing $(date '+%H:%M:%S %Y-%m-%d')"
+          gh release create ${{ inputs.nightly_name }} --verify-tag $addDraft $addPreRelease $addLatest $addTitle $addNotes
           if [[ $? -eq 0 ]]; then
             echo -e "${ANSI_LIGHT_GREEN}[OK]${ANSI_NOCOLOR}"
           else
             echo -e "${ANSI_LIGHT_RED}[FAILED]${ANSI_NOCOLOR}"
             echo "Couldn't create release '${{ inputs.nightly_name }}'."
-            echo "::error title=APIError::Couldn't create release '${{ inputs.nightly_name }}'."
+            echo "::error title=InternalError::Couldn't create release '${{ inputs.nightly_name }}'."
             exit 1
           fi
-
-          # --notes-file <file>
-          # --notes-from-tag
 
       - name: 📥 Download artifacts and upload as assets
         id: uploadAssets
@@ -130,7 +180,7 @@ jobs:
             echo -n "  Checked asset for duplicates ... "
             if [[ -n "${assetFilenames[$asset]}" ]]; then
               echo -e "${ANSI_LIGHT_RED}[ERROR]${ANSI_NOCOLOR}"
-              echo "::error title=DuplicateAsset::Asset '${asset}' was already uploaded to release '${{ inputs.nightly_name }}'."
+              echo "::error title=DuplicateAsset::Asset '${asset}' from artifact '${artifact}' was already uploaded to release '${{ inputs.nightly_name }}'."
               continue
             else
               echo -e "${ANSI_LIGHT_GREEN}[OK]${ANSI_NOCOLOR}"
