Archive with directory.

diff --git a/.github/workflows/Nightly.yml b/.github/workflows/Nightly.yml
--- a/.github/workflows/Nightly.yml
+++ b/.github/workflows/Nightly.yml
@@ -109,7 +109,7 @@ jobs:
             echo -e "${ANSI_LIGHT_YELLOW}[NOT FOUND]${ANSI_NOCOLOR}"
           else
             echo -e "${ANSI_LIGHT_RED}[FAILED]${ANSI_NOCOLOR}"
-            echo "Couldn't delete release '${{ inputs.nightly_name }}' -> Error: '${message}'."
+            echo -e "${ANSI_LIGHT_RED}Couldn't delete release '${{ inputs.nightly_name }}' -> Error: '${message}'.${ANSI_NOCOLOR}"
             echo "::error title=InternalError::Couldn't delete release '${{ inputs.nightly_name }}'."
             exit 1
           fi
@@ -159,7 +159,7 @@ jobs:
             echo -e "${ANSI_LIGHT_GREEN}[OK]${ANSI_NOCOLOR}"
           else
             echo -e "${ANSI_LIGHT_RED}[FAILED]${ANSI_NOCOLOR}"
-            echo "Couldn't create release '${{ inputs.nightly_name }}'."
+            echo -e "${ANSI_LIGHT_RED}Couldn't create release '${{ inputs.nightly_name }}'.${ANSI_NOCOLOR}"
             echo "::error title=InternalError::Couldn't create release '${{ inputs.nightly_name }}'."
             exit 1
           fi
@@ -219,7 +219,7 @@ jobs:
                 echo -e "${ANSI_LIGHT_GREEN}[OK]${ANSI_NOCOLOR}"
               else
                 echo -e "${ANSI_LIGHT_RED}[ERROR]${ANSI_NOCOLOR}"
-                echo "Couldn't download artifact '${artifact}'."
+                echo -e "${ANSI_LIGHT_RED}Couldn't download artifact '${artifact}'.${ANSI_NOCOLOR}"
                 echo "::error title=ArtifactNotFound::Couldn't download artifact '${artifact}'."
                 ERRORS=1
                 continue
@@ -242,37 +242,65 @@ jobs:
                 uploadFile="${asset}"
               else
                 echo -e "    Compression ${ANSI_LIGHT_RED}[ERROR]${ANSI_NOCOLOR}"
-                echo "Couldn't compress '${artifact}' to zip file '${asset}'."
+                echo -e "${ANSI_LIGHT_RED}Couldn't compress '${artifact}' to zip file '${asset}'.${ANSI_NOCOLOR}"
                 echo "::error title=CompressionError::Couldn't compress '${artifact}' to zip file '${asset}'."
                 ERRORS=1
                 continue
               fi
-            elif [[ "${asset}" == !*.tgz || "${asset}" == !*.tar.gz ]]; then
+            elif [[ "${asset}" == !*.tgz || "${asset}" == !*.tar.gz || "${asset}" == \$*.tgz || "${asset}" == \$*.tar.gz ]]; then
               echo -e "${ANSI_LIGHT_GREEN}[TAR/GZ]${ANSI_NOCOLOR}"
-              asset="${asset##*!}"
-              echo "    Compressing artifact '${artifact}' to '${asset}' ..."
-              tar -c --gzip --file="../${asset}" --directory="${artifact}" .
-              if [[ $? -eq 0 ]]; then
+          
+              if [[ "${asset:0:1}" == "\$" ]]; then
+                asset="${asset##*$}"
+                dirName="${asset%.*}"
+                echo "    Compressing artifact '${artifact}' to '${asset}' ..."
+                tar -c --gzip --file="${asset}" --directory="${artifact}" --transform "s|^\.|${dirName%.tar}|" .
+                retCode=$?
+              else
+                asset="${asset##*!}"
+                echo "    Compressing artifact '${artifact}' to '${asset}' ..."
+                (
+                  cd "${artifact}" && \
+                  tar -c --gzip --file="../${asset}" *
+                )
+                retCode=$?
+              fi
+          
+              if [[ $retCode -eq 0 ]]; then
                 echo -e "    Compression ${ANSI_LIGHT_GREEN}[OK]${ANSI_NOCOLOR}"
                 uploadFile="${asset}"
               else
                 echo -e "    Compression ${ANSI_LIGHT_RED}[ERROR]${ANSI_NOCOLOR}"
-                echo "Couldn't compress '${artifact}' to tgz file '${asset}'."
+                echo -e "${ANSI_LIGHT_RED}Couldn't compress '${artifact}' to tgz file '${asset}'.${ANSI_NOCOLOR}"
                 echo "::error title=CompressionError::Couldn't compress '${artifact}' to tgz file '${asset}'."
                 ERRORS=1
                 continue
               fi
-            elif [[ "${asset}" == !*.tzst || "${asset}" == !*.tar.zst ]]; then
+            elif [[ "${asset}" == !*.tzst || "${asset}" == !*.tar.zst || "${asset}" == \$*.tzst || "${asset}" == \$*.tar.zst ]]; then
               echo -e "${ANSI_LIGHT_GREEN}[ZST]${ANSI_NOCOLOR}"
-              asset="${asset##*!}"
-              echo "    Compressing artifact '${artifact}' to '${asset}' ..."
-              tar -c --zstd --file="../${asset}" --directory="${artifact}" --transform 's|^\.|ghdl|' .
-              if [[ $? -eq 0 ]]; then
+          
+              if [[ "${asset:0:1}" == "\$" ]]; then
+                asset="${asset##*$}"
+                dirName="${asset%.*}"
+                echo "    Compressing artifact '${artifact}' to '${asset}' ..."
+                tar -c --zstd --file="${asset}" --directory="${artifact}" --transform "s|^\.|${dirName%.tar}|" .
+                retCode=$?
+              else
+                asset="${asset##*!}"
+                echo "    Compressing artifact '${artifact}' to '${asset}' ..."
+                (
+                  cd "${artifact}" && \
+                  tar -c --zstd --file="../${asset}" *
+                )
+                retCode=$?
+              fi
+          
+              if [[ $retCode -eq 0 ]]; then
                 echo -e "    Compression ${ANSI_LIGHT_GREEN}[OK]${ANSI_NOCOLOR}"
                 uploadFile="${asset}"
               else
                 echo -e "    Compression ${ANSI_LIGHT_RED}[ERROR]${ANSI_NOCOLOR}"
-                echo "Couldn't compress '${artifact}' to zst file '${asset}'."
+                echo -e "${ANSI_LIGHT_RED}Couldn't compress '${artifact}' to zst file '${asset}'.${ANSI_NOCOLOR}"
                 echo "::error title=CompressionError::Couldn't compress '${artifact}' to zst file '${asset}'."
                 ERRORS=1
                 continue
@@ -282,7 +310,7 @@ jobs:
               uploadFile="${artifact}/${asset}"
             else
               echo -e "${ANSI_LIGHT_RED}[ERROR]${ANSI_NOCOLOR}"
-              echo "Couldn't find asset '${asset}' in artifact '${artifact}'."
+              echo -e "${ANSI_LIGHT_RED}Couldn't find asset '${asset}' in artifact '${artifact}'.${ANSI_NOCOLOR}"
               echo "::error title=FileNotFound::Couldn't find asset '${asset}' in artifact '${artifact}'."
               ERRORS=1
               continue
@@ -295,12 +323,12 @@ jobs:
               echo -e "${ANSI_LIGHT_GREEN}[OK]${ANSI_NOCOLOR}"
             else
               echo -e "${ANSI_LIGHT_RED}[ERROR]${ANSI_NOCOLOR}"
-              echo "Couldn't upload asset '${asset}' from '${uploadFile}' to release '${{ inputs.nightly_name }}'."
+              echo -e "${ANSI_LIGHT_RED}Couldn't upload asset '${asset}' from '${uploadFile}' to release '${{ inputs.nightly_name }}'.${ANSI_NOCOLOR}"
               echo "::error title=UploadError::Couldn't upload asset '${asset}' from '${uploadFile}' to release '${{ inputs.nightly_name }}'."
               ERRORS=1
               continue
             fi
-          done <<<"${{ inputs.assets }}"
+          done <<<'${{ inputs.assets }}'
 
           echo "Inspecting downloaded artifacts ..."
           tree -L 3 .
@@ -322,3 +350,5 @@ jobs:
 
           gh pr list --base ${{ inputs.release_branch }} --label Release --state merged --json title --jq '.[0].title'
           echo "return code: $?"
+
+          version=$(gh pr list --base ${{ inputs.release_branch }} --label Release --state merged --json title --jq '.[0].title')
