Extract version number for release.

diff --git a/.github/workflows/Pipeline.yml b/.github/workflows/Pipeline.yml
--- a/.github/workflows/Pipeline.yml
+++ b/.github/workflows/Pipeline.yml
@@ -6,6 +6,48 @@ on:
   workflow_dispatch:
 
 jobs:
+  Version:
+    name: Extract Version from Tag
+    runs-on: ubuntu-24.04
+    if: startsWith(github.ref, 'refs/tags')
+    outputs:
+      version:  ${{ steps.GetVersion.outputs.version }}
+
+    steps:
+      - name: 🖉 Info
+        run: |
+          printf "%s\n" "github.event_name: ${{ github.event_name }}"
+          printf "%s\n" "github.actor:      ${{ github.actor }}"
+          printf "%s\n" "github.ref:        ${{ github.ref }}"
+          printf "%s\n" "github.base_ref:   ${{ github.base_ref }}"
+          printf "%s\n" "github.head_ref:   ${{ github.head_ref }}"
+          printf "%s\n" "github.sha:        ${{ github.sha }}"
+          if [[ -z "$(git rev-list -1 --merges ${{ github.sha }}~1..${{ github.sha }})" ]]; then
+            printf "%s\n" "gitismerge:        normal commit"
+          else
+            printf "%s\n" "gitismerge:        merge commit"
+          fi
+
+      - name: Get version
+        id: GetVersion
+        run: |
+          set +e
+
+          ANSI_LIGHT_RED=$'\x1b[91m'
+          ANSI_LIGHT_BLUE=$'\x1b[94m'
+          ANSI_NOCOLOR=$'\x1b[0m'
+          
+          TAG_PATTERN='^refs/tags/((v|r)?[0-9]+(\.[0-9]+){0,2}(-(dev|alpha|beta|rc)([0-9]*))?)$'
+          if [[ "${{ github.ref }}" =~ $TAG_TAG_PATTERN ]]; then
+            version="${BASH_REMATCH[1]}"
+            printf "version=${version}\n" >> "${GITHUB_OUTPUT}"
+            printf "Version: ${ANSI_LIGHT_BLUE}%s${ANSI_NOCOLOR}\n" "${version}"
+          else
+            printf "${ANSI_LIGHT_RED}Tag '%s' doesn't conform to regexp '%s'.${ANSI_NOCOLOR}\n" "${{ github.ref }}" "${TAG_PATTERN}"
+            printf "::error title=RexExpCheck::Tag '%s' doesn't conform to regexp '%s'.\n" "${{ github.ref }}" "${TAG_PATTERN}"
+            exit 1
+          fi
+
   Build:
     name: Build something
     runs-on: ubuntu-24.04
@@ -99,6 +141,7 @@ jobs:
   Release:
     uses: ./.github/workflows/Nightly.yml
     needs:
+      - Version
       - Build
     if: startsWith(github.ref, 'refs/tags')
     secrets: inherit
@@ -107,8 +150,7 @@ jobs:
       actions: write
 #      attestations: write
     with:
-      prerelease: true
-      nightly_title: "Release"
+      nightly_name: ${{ needs.Version.outputs.version }}
       nightly_description: |
         Full release
 
